# -*- coding: utf-8 -*-

################################################################################
# Form generated from reading UI file 'SocketTest_multi.ui'
##
# Created by: Qt User Interface Compiler version 6.5.1
##
# WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QComboBox, QGroupBox,
                               QLabel, QLineEdit, QMainWindow, QPushButton,
                               QRadioButton, QSizePolicy, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(712, 495)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.title = QLabel(self.centralwidget)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(11, 10, 691, 32))
        font = QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.title.setFont(font)
        self.title.setAlignment(Qt.AlignCenter)
        self.title.setIndent(5)
        self.server_addr = QGroupBox(self.centralwidget)
        self.server_addr.setObjectName(u"server_addr")
        self.server_addr.setGeometry(QRect(10, 60, 241, 221))
        font1 = QFont()
        font1.setBold(True)
        self.server_addr.setFont(font1)
        self.input_port = QLineEdit(self.server_addr)
        self.input_port.setObjectName(u"input_port")
        self.input_port.setGeometry(QRect(69, 90, 71, 27))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.input_port.setFont(font2)
        self.input_port.setAlignment(Qt.AlignCenter)
        self.com_check = QPushButton(self.server_addr)
        self.com_check.setObjectName(u"com_check")
        self.com_check.setEnabled(False)
        self.com_check.setGeometry(QRect(10, 150, 221, 51))
        self.com_check.setIconSize(QSize(16, 20))
        self.ip_address = QLabel(self.server_addr)
        self.ip_address.setObjectName(u"ip_address")
        self.ip_address.setGeometry(QRect(10, 40, 53, 21))
        self.ip_address.setFont(font2)
        self.ip_address.setAlignment(Qt.AlignCenter)
        self.input_ip_addr = QLineEdit(self.server_addr)
        self.input_ip_addr.setObjectName(u"input_ip_addr")
        self.input_ip_addr.setGeometry(QRect(69, 40, 161, 27))
        self.input_ip_addr.setFont(font2)
        self.port = QLabel(self.server_addr)
        self.port.setObjectName(u"port")
        self.port.setGeometry(QRect(10, 90, 32, 21))
        self.port.setFont(font2)
        self.port.setAlignment(Qt.AlignCenter)
        self.data_type = QGroupBox(self.centralwidget)
        self.data_type.setObjectName(u"data_type")
        self.data_type.setGeometry(QRect(268, 60, 431, 221))
        self.data_type.setFont(font1)
        self.modem = QLabel(self.data_type)
        self.modem.setObjectName(u"modem")
        self.modem.setGeometry(QRect(11, 27, 70, 21))
        self.modem.setFont(font2)
        self.modem.setAlignment(Qt.AlignCenter)
        self.lora_modem = QRadioButton(self.data_type)
        self.select_modem = QButtonGroup(MainWindow)
        self.select_modem.setObjectName(u"select_modem")
        self.select_modem.addButton(self.lora_modem)
        self.lora_modem.setObjectName(u"lora_modem")
        self.lora_modem.setGeometry(QRect(161, 26, 56, 25))
        self.lora_modem.setFont(font2)
        self.lora_modem.setCursor(QCursor(Qt.PointingHandCursor))
        self.lora_modem.setAutoFillBackground(False)
        self.lora_modem.setChecked(True)
        self.lte_modem = QRadioButton(self.data_type)
        self.select_modem.addButton(self.lte_modem)
        self.lte_modem.setObjectName(u"lte_modem")
        self.lte_modem.setGeometry(QRect(251, 26, 47, 25))
        self.lte_modem.setFont(font2)
        self.lte_modem.setCursor(QCursor(Qt.PointingHandCursor))
        self.lte_modem.setLayoutDirection(Qt.LeftToRight)
        self.lte_modem.setIconSize(QSize(20, 20))
        self.lte_modem.setAutoRepeatInterval(100)
        self.type = QLabel(self.data_type)
        self.type.setObjectName(u"type")
        self.type.setGeometry(QRect(11, 58, 54, 21))
        self.type.setFont(font2)
        self.type.setAlignment(Qt.AlignCenter)
        self.single_type = QRadioButton(self.data_type)
        self.select_type = QButtonGroup(MainWindow)
        self.select_type.setObjectName(u"select_type")
        self.select_type.addButton(self.single_type)
        self.single_type.setObjectName(u"single_type")
        self.single_type.setGeometry(QRect(161, 57, 55, 25))
        self.single_type.setFont(font2)
        self.single_type.setCursor(QCursor(Qt.PointingHandCursor))
        self.single_type.setChecked(True)
        self.triple_type = QRadioButton(self.data_type)
        self.select_type.addButton(self.triple_type)
        self.triple_type.setObjectName(u"triple_type")
        self.triple_type.setGeometry(QRect(251, 57, 48, 25))
        self.triple_type.setFont(font2)
        self.triple_type.setCursor(QCursor(Qt.PointingHandCursor))
        self.triple_type.setLayoutDirection(Qt.LeftToRight)
        self.triple_type.setIconSize(QSize(20, 20))
        self.triple_type.setAutoRepeatInterval(100)
        self.mppt = QLabel(self.data_type)
        self.mppt.setObjectName(u"mppt")
        self.mppt.setGeometry(QRect(11, 89, 82, 21))
        self.mppt.setFont(font2)
        self.mppt.setAlignment(Qt.AlignCenter)
        self.no_mppt = QRadioButton(self.data_type)
        self.select_mppt = QButtonGroup(MainWindow)
        self.select_mppt.setObjectName(u"select_mppt")
        self.select_mppt.addButton(self.no_mppt)
        self.no_mppt.setObjectName(u"no_mppt")
        self.no_mppt.setGeometry(QRect(161, 88, 71, 25))
        self.no_mppt.setFont(font2)
        self.no_mppt.setCursor(QCursor(Qt.PointingHandCursor))
        self.no_mppt.setChecked(True)
        self.yes_mppt = QRadioButton(self.data_type)
        self.select_mppt.addButton(self.yes_mppt)
        self.yes_mppt.setObjectName(u"yes_mppt")
        self.yes_mppt.setGeometry(QRect(251, 88, 55, 25))
        self.yes_mppt.setFont(font2)
        self.yes_mppt.setCursor(QCursor(Qt.PointingHandCursor))
        self.yes_mppt.setLayoutDirection(Qt.LeftToRight)
        self.yes_mppt.setIconSize(QSize(20, 20))
        self.yes_mppt.setAutoRepeatInterval(100)
        self.error = QLabel(self.data_type)
        self.error.setObjectName(u"error")
        self.error.setGeometry(QRect(11, 120, 108, 21))
        self.error.setFont(font2)
        self.error.setAlignment(Qt.AlignCenter)
        self.no_err = QRadioButton(self.data_type)
        self.select_err = QButtonGroup(MainWindow)
        self.select_err.setObjectName(u"select_err")
        self.select_err.addButton(self.no_err)
        self.no_err.setObjectName(u"no_err")
        self.no_err.setGeometry(QRect(161, 119, 55, 25))
        self.no_err.setFont(font2)
        self.no_err.setCursor(QCursor(Qt.PointingHandCursor))
        self.no_err.setChecked(True)
        self.yes_err = QRadioButton(self.data_type)
        self.select_err.addButton(self.yes_err)
        self.yes_err.setObjectName(u"yes_err")
        self.yes_err.setGeometry(QRect(251, 119, 93, 25))
        self.yes_err.setFont(font2)
        self.yes_err.setCursor(QCursor(Qt.PointingHandCursor))
        self.yes_err.setLayoutDirection(Qt.LeftToRight)
        self.yes_err.setIconSize(QSize(20, 20))
        self.yes_err.setAutoRepeatInterval(100)
        self.err_level = QComboBox(self.data_type)
        self.err_level.setObjectName(u"err_level")
        self.err_level.setEnabled(False)
        self.err_level.setGeometry(QRect(350, 120, 69, 22))
        self.com = QLabel(self.data_type)
        self.com.setObjectName(u"com")
        self.com.setGeometry(QRect(11, 151, 108, 21))
        self.com.setFont(font2)
        self.com_success = QRadioButton(self.data_type)
        self.select_com = QButtonGroup(MainWindow)
        self.select_com.setObjectName(u"select_com")
        self.select_com.addButton(self.com_success)
        self.com_success.setObjectName(u"com_success")
        self.com_success.setGeometry(QRect(161, 150, 55, 25))
        self.com_success.setFont(font2)
        self.com_success.setCursor(QCursor(Qt.PointingHandCursor))
        self.com_success.setChecked(True)
        self.com_fail = QRadioButton(self.data_type)
        self.select_com.addButton(self.com_fail)
        self.com_fail.setObjectName(u"com_fail")
        self.com_fail.setGeometry(QRect(251, 150, 93, 25))
        self.com_fail.setFont(font2)
        self.com_fail.setCursor(QCursor(Qt.PointingHandCursor))
        self.com_fail.setLayoutDirection(Qt.LeftToRight)
        self.com_fail.setIconSize(QSize(20, 20))
        self.com_fail.setAutoRepeatInterval(100)
        self.device_set = QLabel(self.data_type)
        self.device_set.setObjectName(u"device_set")
        self.device_set.setGeometry(QRect(10, 180, 111, 21))
        self.device_set.setFont(font2)
        self.device_multi = QRadioButton(self.data_type)
        self.select_count = QButtonGroup(MainWindow)
        self.select_count.setObjectName(u"select_count")
        self.select_count.addButton(self.device_multi)
        self.device_multi.setObjectName(u"device_multi")
        self.device_multi.setGeometry(QRect(250, 180, 93, 25))
        self.device_multi.setFont(font2)
        self.device_multi.setCursor(QCursor(Qt.PointingHandCursor))
        self.device_multi.setLayoutDirection(Qt.LeftToRight)
        self.device_multi.setIconSize(QSize(20, 20))
        self.device_multi.setAutoRepeatInterval(100)
        self.device_single = QRadioButton(self.data_type)
        self.select_count.addButton(self.device_single)
        self.device_single.setObjectName(u"device_single")
        self.device_single.setGeometry(QRect(160, 180, 55, 25))
        self.device_single.setFont(font2)
        self.device_single.setCursor(QCursor(Qt.PointingHandCursor))
        self.device_single.setChecked(True)
        self.device_num = QComboBox(self.data_type)
        self.device_num.setObjectName(u"device_num")
        self.device_num.setEnabled(False)
        self.device_num.setGeometry(QRect(350, 180, 69, 22))
        self.run_btn = QPushButton(self.centralwidget)
        self.run_btn.setObjectName(u"run_btn")
        self.run_btn.setEnabled(False)
        self.run_btn.setGeometry(QRect(10, 420, 431, 41))
        self.exit_btn = QPushButton(self.centralwidget)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(450, 420, 251, 41))
        self.test_result = QGroupBox(self.centralwidget)
        self.test_result.setObjectName(u"test_result")
        self.test_result.setGeometry(QRect(10, 287, 691, 121))
        self.test_result.setFont(font1)
        self.com_result = QLabel(self.test_result)
        self.com_result.setObjectName(u"com_result")
        self.com_result.setGeometry(QRect(16, 20, 661, 91))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(False)
        self.com_result.setFont(font3)
        self.com_result.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate(
            "MainWindow", u"RTU Socket Client", None))
        self.title.setText(QCoreApplication.translate(
            "MainWindow", u"RTU \uac00\uc0c1 \uc18c\ucf13\ud1b5\uc2e0 \ud14c\uc2a4\ud2b8 Tool", None))
        self.server_addr.setTitle(QCoreApplication.translate(
            "MainWindow", u"\uc18c\ucf13 \uc11c\ubc84 \uc8fc\uc18c \uc785\ub825", None))
        self.input_port.setText("")
        self.com_check.setText(QCoreApplication.translate(
            "MainWindow", u"\uc5f0\uacb0 \uc720\ud6a8\uc131 \uac80\uc0ac", None))
        self.ip_address.setText(QCoreApplication.translate(
            "MainWindow", u"IP \uc8fc\uc18c", None))
        self.input_ip_addr.setText("")
        self.port.setText(QCoreApplication.translate(
            "MainWindow", u"\ud3ec\ud2b8", None))
        self.data_type.setTitle(QCoreApplication.translate(
            "MainWindow", u"\ub370\uc774\ud130 \ud0c0\uc785 \uc124\uc815", None))
        self.modem.setText(QCoreApplication.translate(
            "MainWindow", u"\ubaa8\ub380 \ud0c0\uc785", None))
        self.lora_modem.setText(
            QCoreApplication.translate("MainWindow", u"Lora", None))
        self.lte_modem.setText(
            QCoreApplication.translate("MainWindow", u"LTE", None))
        self.type.setText(QCoreApplication.translate(
            "MainWindow", u"\uc0c1 \uad6c\ubd84", None))
        self.single_type.setText(QCoreApplication.translate(
            "MainWindow", u"\ub2e8\uc0c1", None))
        self.triple_type.setText(QCoreApplication.translate(
            "MainWindow", u"3\uc0c1", None))
        self.mppt.setText(QCoreApplication.translate(
            "MainWindow", u"MPPT \ubaa8\ub4dc", None))
        self.no_mppt.setText(QCoreApplication.translate(
            "MainWindow", u"\ubbf8\ud3ec\ud568", None))
        self.yes_mppt.setText(QCoreApplication.translate(
            "MainWindow", u"\ud3ec\ud568", None))
        self.error.setText(QCoreApplication.translate(
            "MainWindow", u"\uc5d0\ub7ec \uc0c1\ud0dc \uc124\uc815", None))
        self.no_err.setText(QCoreApplication.translate(
            "MainWindow", u"\uc815\uc0c1", None))
        self.yes_err.setText(QCoreApplication.translate(
            "MainWindow", u"\uc5d0\ub7ec \uc801\uc6a9", None))
        self.com.setText(QCoreApplication.translate(
            "MainWindow", u"\ud1b5\uc2e0 \uc0c1\ud0dc \uc124\uc815", None))
        self.com_success.setText(QCoreApplication.translate(
            "MainWindow", u"\uc815\uc0c1", None))
        self.com_fail.setText(QCoreApplication.translate(
            "MainWindow", u"\ud1b5\uc2e0 \uc2e4\ud328", None))
        self.device_set.setText(QCoreApplication.translate(
            "MainWindow", u"\uc7a5\ube44 \ub300\uc218 \uc124\uc815", None))
        self.device_multi.setText(QCoreApplication.translate(
            "MainWindow", u"\uba40\ud2f0", None))
        self.device_single.setText(QCoreApplication.translate(
            "MainWindow", u"\ub2e8\uc77c", None))
        self.run_btn.setText(QCoreApplication.translate(
            "MainWindow", u"\uc2e4\ud589", None))
        self.exit_btn.setText(QCoreApplication.translate(
            "MainWindow", u"\uc885\ub8cc", None))
        self.test_result.setTitle(QCoreApplication.translate(
            "MainWindow", u"\uc5f0\uacb0 \uc720\ud6a8\uc131 \uac80\uc0ac \uacb0\uacfc", None))
        self.com_result.setText(QCoreApplication.translate(
            "MainWindow", u"\uc720\ud6a8\uc131 \uac80\uc0ac\ub97c \uc2e4\uc2dc\ud574\uc8fc\uc138\uc694.", None))
    # retranslateUi
