version: "3.8"

services:

  frontend:
    build:
      context: ./Frontend/dashboard/.
      dockerfile: Dockerfile
    container_name: DA_frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./Frontend/dashboard:/src
      - ./Frontend/dashboard/assets:/assets
    depends_on:
      - backend
    networks:
      dash_net:
        aliases:
          - frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start

  backend:
    build:
      context: ./Backend/.
      dockerfile: Dockerfile
    container_name: DA_backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/src
      - ./Backend/assets:/assets
    networks:
      dash_net:
        aliases:
          - backend
    external_links:
      - DA_redis
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000

  redis:
    image: redis:latest
    container_name: DA_redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dash_net

networks:
  dash_net:
      driver: bridge
