# 베이스 이미지로 Python 3.9 이미지를 사용합니다.
FROM python:3.9-slim

# 작업 디렉토리를 설정합니다.
WORKDIR /app

# 현재 디렉토리의 모든 파일을 컨테이너의 /app 디렉토리로 복사합니다.
COPY . /app

# 필요한 라이브러리를 설치합니다.
RUN pip install paho-mqtt

# 컨테이너가 실행될 때 실행할 명령을 지정합니다.
CMD ["python", "publisher.py"]